name: Playwright NVDA

on:
  push:
    branches: [main, add-screen-reading]
  pull_request:
    branches: [main, add-screen-reading]

jobs:
  playwright-nvda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        browser: [chromium]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Guidepup Setup
        uses: guidepup/setup-action@0.15.3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Storybook
        run: npm run build-storybook
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Serve Storybook and run tests
        run: npx --yes concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "npx --yes http-server ./storybook-static --port 2001 --silent" "npx wait-on http://127.0.0.1:2001 && set READER=nvda npx test-storybook --maxWorkers 1 --browsers chromium --url http://127.0.0.1:2001"
