
name: 'UI Tests on Windows'

on: push

jobs:
  # Run interaction and accessibility tests
  interaction-and-accessibility:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          npm install concurrently wait-port http-server -g
      - name: Build Storybook
        run: npm run build-storybook
      - name: Install Playwright
        run: |
          npx playwright install chromium firefox
      - name: Serve Storybook and run tests
        env:
          HEADLESS: true
        run: |
          npx --yes concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "npx --yes http-server ./storybook-static --port 6006 --silent" "npx wait-port http://127.0.0.1:6006/iframe.html && set HEADLESS=true npx test-storybook --index-json --verbose --url http://127.0.0.1:6006 --coverage --coverageDirectory .storybook && nyc report --reporter=text -t .storybook"