
name: 'UI Tests on Windows'

on: push

jobs:
  # Run interaction and accessibility tests
  interaction-and-accessibility:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          npm install concurrently wait-on http-server -g
      - name: Build Storybook
        run: npm run build-storybook
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "npx http-server ./storybook-static -p 6006" "npx wait-on tcp:6006 && set HEADLESS=true npx test-storybook --verbose"